---
abstract: 'Client library for Huahin Manager.'
author:
  - 'TAGOMORI Satoshi <tagomoris {at} gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Hadoop-HuahinManager
no_index:
  directory:
    - inc
    - t
requires:
  Furl: 0
  JSON: 0
  JSON::XS: 0
  Test::More: 0
  Try::Tiny: 0
  URI::Escape: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
